modLoader="javafml"
loaderVersion="[41,)"
license="BSD (3 clause)"
issueTrackerURL="https://github.com/gigaherz/InventorySpam/issues"

[[mods]]
modId="inventoryspam"
version="${file.jarVersion}"
displayName="Inventory Spam"
description='''
Shows the items added and removed from the inventory
'''
displayURL="https://github.com/gigaherz/InventorySpam"
logoFile="logo.png"
authors="gigaherz"

[[dependencies.inventoryspam]]
    modId="forge"
    mandatory=true
    versionRange="[41.0.64,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.inventoryspam]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,1.20)"
    ordering="NONE"
    side="BOTH"