modLoader="javafml" #mandatory
loaderVersion="[37,)" #mandatory
issueTrackerURL="https://github.com/gigaherz/InventorySpam/issues" #optional
displayURL="https://github.com/gigaherz/InventorySpam" #optional
logoFile="logo.png" #optional
credits="Thanks for this example mod goes to Java" #optional
authors="gigaherz" #optional
license="BSD (3 clause)"

[[mods]] #mandatory
modId="inventoryspam" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Inventory Spam" #mandatory
description='''
Shows the items added and removed from the inventory
'''

[[dependencies.inventoryspam]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[37.0.59,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.inventoryspam]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17.1,1.18)"
    ordering="NONE"
    side="BOTH"