modLoader="javafml"
loaderVersion="[1,)"
license="BSD (3 clause)"
issueTrackerURL="https://github.com/gigaherz/InventorySpam/issues"

[[mods]]
modId="inventoryspam"
version="${file.jarVersion}"
displayName="Inventory Spam"
description='''
Shows the items added and removed from the inventory
'''
displayURL="https://github.com/gigaherz/InventorySpam"
logoFile="logo.png"
authors="gigaherz"
displayTest="IGNORE_ALL_VERSION"

[[mixins]]
    config="inventoryspam.mixins.json"

[[dependencies.inventoryspam]]
    modId="neoforge"
    type="required"
    versionRange="[21.5.20-beta,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.inventoryspam]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.5,1.22)"
    ordering="NONE"
    side="BOTH"