@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package gigaherz.inventoryspam;

import com.mojang.logging.annotations.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;