@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package gigaherz.inventoryspam;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;